version: '3'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception-network

  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
      - nginx
    container_name: wordpress
    restart: always
    volumes:
      - WordPress:/var/www/html
    expose: 
      - "9000"
    networks:
      - inception-network
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge
    
volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dmercadi/data/wordpress'
  DB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dmercadi/data/db' 