version: '3'
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - 443:443
      - 9000:9000
    #restart: always
    volumes:
      - /home/dmercadi/data/wordpress:/var/www/html
    networks:
      - inception-network
  # wordpress:
  #   build: requirements/wordpress/
  #   depends_on:
  #     - mariadb
  #   container_name: wordpress
  #   restart: always
  #   volumes:
  #     - /home/dmercadi/data/wordpress:/var/www/html
  #   ports:
  #     - 9000:9000
  #     - 3306:3306
  #   networks:
  #     - inception-network
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    #restart: always
    volumes:
      - /home/dmercadi/data/db:/var/lib/mysql
    environment:
      - DATABASE_NAME=test
      - DATABASE_USER=usertest
      - DATABASE_PASSWORD=passtest
    ports:
      - 3306:3306
    networks:
      - inception-network
networks:
  inception-network: