version: '3'
env-file: .env
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    # image:  nginx:1.0
    depends_on:
      - wordpress
    ports:
      - 443:443
      - 9000:9000
    restart: always
    volumes:
      - /home/dmercadi/data/wordpress:/var/www/html
  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    container_name: nginx
    restart: always
    volumes:
      - /home/dmercadi/data/wordpress:/var/www/html
    port:
      - 9000:9000
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - /home/dmercadi/data/db:/var/lib/mysql
    port:
      - 3306:3306

# volumes:
#   WordPress: