version: '3'
services:
  nginx:
    build: 
      context: requirements/nginx/
      env_file: .env
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - 443:443
    #  - 9000:9000
    #restart: always
    volumes:
      - /home/dmercadi/data/wordpress:/var/www/html
    networks:
      - inception-network
  # wordpress:
  #   build: requirements/wordpress/
  #   depends_on:
  #     - mariadb
  #   container_name: wordpress
  #   restart: always
  #   volumes:
  #     - /home/dmercadi/data/wordpress:/var/www/html
  #   ports:
  #     - 9000:9000
  #     - 3306:3306
  #   networks:
  #     - inception-network
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb/
      env_file: .env
    #restart: always
    volumes:
      - /home/dmercadi/data/db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - inception-network
networks:
  inception-network: