version: '3'
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - 443:443
      - 9000:9000
    #restart: always
    volumes:
      - /home/dmercadi/data/wordpress:/var/www/html
    networks:
      - inception-network
  # wordpress:
  #   build: requirements/wordpress/
  #   depends_on:
  #     - mariadb
  #   container_name: wordpress
  #   restart: always
  #   volumes:
  #     - /home/dmercadi/data/wordpress:/var/www/html
  #   ports:
  #     - 9000:9000
  #     - 3306:3306
  #   networks:
  #     - inception-network
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/
      args:
        DATABASE_NAME: "${DATABASE_NAME}"
        DATABASE_USER: "${DATABASE_USER}"
        DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    container_name: mariadb
    #restart: always
    volumes:
      - /home/dmercadi/data/db:/var/lib/mysql
    environment:
    ports:
      - 3306:3306
    networks:
      - inception-network
networks:
  inception-network: