version: '3'
services:
  nginx:
    build: requirements/nginx/
    # container_name: nginx
    image:  nginx:1.0
    ports:
      - 443:443
      - 9000:9000
    restart: always
    # volumes:
    #   - WordPress
  # wordpress:
  #   build: requirements/wordpress/
  #   image: wordpress:1.0
  #   restart: always
  #   volumes:
  #     - WordPress
# volumes:
#   WordPress
#   DB