version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception-network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    expose:
      - "3306"
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - WordPress:/var/www/wordpress
    networks:
      - inception-network
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
    - WordPress:/var/www/wordpress
    networks:
      - inception-network
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    expose: 
      - "9000"
volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dmercadi/data/wordpress'
  DB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dmercadi/data/mariadb'
networks:
    inception-network:
      driver: bridge
