# start from the latest version of the Debian operating system
FROM debian:10.12

# update the package repository and install Nginx
RUN apt-get update
RUN wget https://wordpress.org/latest.zip && unzip latest.zip

